trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*
    - features/*
  paths:
    exclude: [ 'README.md' ]

jobs:
- job: BuildWindows

  pool:
    vmImage: 'windows-latest'

  variables:
    SDK_VERSION: 0.0.39
    pythonVersion: 3.10
    BUILD_PATH: $(Build.BinariesDirectory)\win32
    PYTHON_DIR: $(Build.BinariesDirectory)\win32\cpython-3.10.0-x86_64
    PYTHON_EXE: $(Build.BinariesDirectory)\win32\cpython-3.10.0-x86_64\python.exe
    PYTHON_SCRIPTS_DIR: $(Build.BinariesDirectory)\win32\cpython-3.10.0-x86_64\Scripts
    SDK_HOME_DIR: $(Build.BinariesDirectory)\win32\SDK_HOME_DIR
    SDK_REPO_DIR: $(Build.BinariesDirectory)\win32\sdk_repo
    SDK_LOG_LEVEL: DEBUG
    SDK_PORTABLE_MODE: 1
    SDK_SKIP_POSTGRES_INIT: 1

  steps:
    - script: |
        mkdir -p $(SDK_HOME_DIR)
    - template: windows.yaml

- job: BuildLinux

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    SDK_VERSION: 0.0.39
    pythonVersion: 3.10
    BUILD_PATH: $(Build.BinariesDirectory)/linux
    PYTHON_DIR: $(Build.BinariesDirectory)/linux/cpython-3.10.0-x86_64
    PYTHON_EXE: $(Build.BinariesDirectory)/linux/cpython-3.10.0-x86_64/python/install/bin/python3
    PYTHON_SCRIPTS_DIR: $(Build.BinariesDirectory)/linux/cpython-3.10.0-x86_64/python/install/bin
    SDK_HOME_DIR: $(Build.BinariesDirectory)/linux/SDK_HOME_DIR
    SDK_REPO_DIR: $(Build.BinariesDirectory)/linux/sdk_repo

    PYTHON_SITE_PACKAGES: $(Build.BinariesDirectory)/linux/cpython-3.10.0-x86_64/python/install/lib/python$(pythonVersion)/site-packages
    SDK_LOG_LEVEL: DEBUG
    SDK_POSTGRES_PORT: 55432
    SDK_PORTABLE_MODE: 1
    SDK_SKIP_POSTGRES_INIT: 1

  steps:
    - script: |
        mkdir -p $(SDK_HOME_DIR)
    - template: linux.yaml

- job: BuildMacOSX

  pool:
    vmImage: 'macOS-10.15'

  variables:
    SDK_VERSION: 0.0.39
    pythonVersion: 3.10
    BUILD_PATH: $(Build.BinariesDirectory)/macos
    PYTHON_DIR: $(Build.BinariesDirectory)/macos/cpython-3.10.0-x86_64
    PYTHON_EXE: $(Build.BinariesDirectory)/macos/cpython-3.10.0-x86_64/python/install/bin/python3
    PYTHON_SCRIPTS_DIR: $(Build.BinariesDirectory)/macos/cpython-3.10.0-x86_64/python/install/bin
    SDK_HOME_DIR: $(Build.BinariesDirectory)/macos/SDK_HOME_DIR
    SDK_REPO_DIR: $(Build.BinariesDirectory)/macos/sdk_repo

    PYTHON_SITE_PACKAGES: $(Build.BinariesDirectory)/macos/cpython-3.10.0-x86_64/python/install/lib/python$(pythonVersion)/site-packages
    SDK_LOG_LEVEL: DEBUG
    SDK_POSTGRES_PORT: 55432
    SDK_PORTABLE_MODE: 1
    SDK_SKIP_POSTGRES_INIT: 1

  steps :
    - script: |
        mkdir -p $(SDK_HOME_DIR)
    - template: macos.yaml
